#!/usr/bin/env ruby

require_relative "lib/rami"
require "mongo"
require "yaml"
include Mongo

config = YAML.load_file("#{File.dirname(__FILE__)}/config.yml")["rami"]

$0 = "RAMI Daemon"
RAMI::Daemon.start(fork, config["pidfile"],
                   "#{File.dirname(__FILE__)}/#{config["action_log"]}",
                   "#{File.dirname(__FILE__)}/#{config["error_log"]}")
Signal.trap("HUP")  { $stdout.puts "SIGHUP and exit";  exit }
Signal.trap("INT")  { $stdout.puts "SIGINT and exit";  exit }
Signal.trap("QUIT") { $stdout.puts "SIGQUIT and exit"; exit }

db = Connection.new.db(config["mongo_db"])
events = db.collection(config["mongo_collection"])

login = "Action: login\nUsername: #{config["username"]}\nSecret: #{config["secret"]}\nEvent: on\n\n"

buffer = ""
h = {}

Thread.new do
  loop do
    st = RAMI::Listener.new(config["host"], config["port"])
    buffer = ""
    if st.sock
      st.login(login)
      while !st.sock.closed?
        st.run do
          data = st.data
          begin
            if data =~ /\r\n\r\n$/ && buffer.empty?
              data.split("\r\n\r\n").each do |d|
                h = RAMI::fields(d.split("\r\n"))
                events.insert(h) if h[:event] == "Cdr"
              end
            else
              buffer += data
            end
            if buffer =~ /\r\n\r\n$/
              buffer.split("\r\n\r\n").each do |d|
                h = RAMI::fields(d.split("\r\n"))
                events.insert(h) if h[:event] == "Cdr"
              end
              buffer = ""
            end
          rescue
            puts "[#{Time.now}] #{data}"
          end
        end
      end
    end
    sleep 1
  end
end.join
